import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'

function MyApp({ Component, pageProps }: AppProps) {
  return (
  <div className="h-screen w-screen flex flex-col justify-between items-center relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Component {...pageProps} />
      </main>
      <footer>
        <a href="http://github.com/dolfolife/">github</a>
      </footer>
  </div>);
}

export default MyApp
