name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
    - 'resume/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get version
      id: version
      run: echo ::set-output name=version::$(cat resume/VERSION)
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      env:
        version: ${{ steps.version.outputs.version }}
      with:
        context: ./resume
        push: true
        tags: dolfolife/latex:$version
