name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
    - 'resume/Dockerfile'
    - 'resume/VERSION'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get version
      id: version
      run: echo "version=$(cat resume/VERSION)" >> $GITHUB_ENV
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./resume
        push: true
        tags: dolfolife/latex:${{ env.version }}
    - name: Create Tag
      id: tag
      env:
        tag: "latex-dockerfile/v${{ env.version }}"
      run: |
        git tag $tag
        git push --tags
        echo "tag=$tag" >> $GITHUB_ENV
