name: Build and Release Resume
on:
  workflow_dispatch: {}
#  push:
#    branches: [ main ]
#    paths:
#    - 'resume/resume.tex'
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get version
      id: version
      run: echo ::set-output name=version::$(cat resume/VERSION) 
    - name: Build
      id: build
      uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        image: dolfolife/latex:${{ steps.version.outputs.version }}
        options: -v ${{ github.workspace }}:/resume --net=none
        shell: bash
        run: |
          echo "Running Script"
          pushd resume
            pdflatex resume.tex && pdflatex resume.tex
          popd
          echo "::set-output name=resume_file::resume/resume.pdf"
    - name: Create Tag
      id: tag
      env:
        tag: "resume/v${{ steps.version.outputs.version }}"
      run: |
        git tag $tag
        git push --tags
        echo "::set-output name=tag::$tag"
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Resume v${{ steps.version.outputs.version }}
        tag_name: ${{ steps.tag.outputs.tag }}
        files: |
          ${{ steps.build.outputs.resume_file }}
        token: ${{ secrets.GITHUB_TOKEN }}
