name: Build and Release Resume
on:
  workflow_dispatch: {}
#  push:
#    branches: [ main ]
#    paths:
#    - 'resume/resume.tex'
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get version
      id: version
      run: echo "{version}=$(cat resume/VERSION)" >> $GITHUB_OUTPUT
    - name: Build
      id: build
      uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        image: dolfolife/latex:${{ steps.version.outputs.version }}
        options: -v ${{ github.workspace }}:/resume --net=none
        shell: bash
        run: |
          echo "Running Script"
          pushd resume
            pdflatex resume.tex && pdflatex resume.tex
          popd
          echo "{resume_file}={${{ github.workspace }}/resume/resume.pdf}" >> $GITHUB_OUTPUT
    - name: Create Tag
      id: tag
      env:
        tag: "resume/v${{ steps.version.outputs.version }}"
      run: |
        git tag $tag
        git push --tags
        echo "{tag}=$tag" >> $GITHUB_OUTPUT
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Resume v${{ steps.version.outputs.version }}
        tag_name: ${{ steps.tag.outputs.tag }}
        files: |
          ${{ github.workspace }}:/resume/resume.pdf
        token: ${{ secrets.GITHUB_TOKEN }}
